begin;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  student_id text not null unique check (student_id ~ '^AU[0-9]{7}$'),
  full_name text not null check (char_length(full_name) >= 2),
  program text not null default '',
  avatar_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists is_admin boolean not null default false;
alter table public.profiles add column if not exists semester integer;
do $$ begin
  alter table public.profiles add constraint profiles_semester_check check (semester between 1 and 8);
exception when duplicate_object then null; end $$;
alter table public.profiles add column if not exists academic_level text;
do $$ begin
  alter table public.profiles add constraint profiles_academic_level_check check (academic_level in ('foundation','semester-1','semester-2','semester-3','semester-4','bachelor'));
exception when duplicate_object then null; end $$;
alter table public.profiles add column if not exists major text;
do $$ begin
  alter table public.profiles add constraint profiles_major_check check (major in ('CS','NW','ME','EE'));
exception when duplicate_object then null; end $$;
update public.profiles set academic_level='semester-2' where semester=2 and academic_level is null;

create table if not exists public.academic_assignments (
  email text primary key,
  academic_level text not null check (academic_level in ('foundation','semester-1','semester-2','semester-3','semester-4','bachelor')),
  major text check (major in ('CS','NW','ME','EE')),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint academic_assignments_official_email check (email ~ '^[^@\s]+@(st\.auston\.edu\.mm|auston\.edu\.mm)$')
);

alter table public.academic_assignments add column if not exists major text;
do $$ begin
  alter table public.academic_assignments add constraint academic_assignments_major_check check (major in ('CS','NW','ME','EE'));
exception when duplicate_object then null; end $$;

insert into public.academic_assignments(email,academic_level,major)
select lower(email),academic_level,major from public.profiles where academic_level is not null
on conflict (email) do update set academic_level=excluded.academic_level,major=excluded.major,updated_at=now();

create table if not exists public.timetable (
  id bigint generated by default as identity primary key,
  title text not null,
  lecturer text not null default '',
  room text not null default '',
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  cohort text not null default 'all',
  published boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.timetable add column if not exists target_user_id uuid references public.profiles(id) on delete cascade;
alter table public.timetable add column if not exists created_by uuid references public.profiles(id) on delete set null;
alter table public.timetable add column if not exists source text not null default 'official';
alter table public.timetable add column if not exists external_ref text;
alter table public.timetable add column if not exists target_major text;
create unique index if not exists timetable_external_ref_key on public.timetable(external_ref) where external_ref is not null;
do $$ begin
  alter table public.timetable add constraint timetable_source_check check (source in ('official','personal'));
exception when duplicate_object then null; end $$;
do $$ begin
  alter table public.timetable add constraint timetable_target_major_check check (target_major in ('CS','NW','ME','EE'));
exception when duplicate_object then null; end $$;

create table if not exists public.content_items (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('deadline','notice','job','news','event')),
  title text not null,
  body text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  published_at timestamptz not null default now(),
  published boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.content_items add column if not exists target_user_id uuid references public.profiles(id) on delete cascade;
alter table public.content_items add column if not exists created_by uuid references public.profiles(id) on delete set null;

create table if not exists public.otp_request_limits (
  email text primary key,
  request_count integer not null default 0 check (request_count between 0 and 4),
  window_started_at timestamptz not null default now(),
  last_requested_at timestamptz
);

create or replace function public.claim_otp_request(p_email text)
returns table(allowed boolean, remaining integer, retry_after_seconds integer)
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_email text := lower(trim(p_email));
  current_count integer;
  window_start timestamptz;
begin
  if normalized_email !~ '^[^@\s]+@(st\.auston\.edu\.mm|auston\.edu\.mm)$' then
    raise exception 'Only official Auston email addresses are allowed';
  end if;

  insert into public.otp_request_limits(email)
  values(normalized_email)
  on conflict (email) do nothing;

  select request_count, window_started_at
  into current_count, window_start
  from public.otp_request_limits
  where email = normalized_email
  for update;

  if window_start <= now() - interval '1 hour' then
    current_count := 0;
    window_start := now();
    update public.otp_request_limits
    set request_count = 0, window_started_at = window_start
    where email = normalized_email;
  end if;

  if current_count >= 4 then
    return query select false, 0,
      greatest(1, ceil(extract(epoch from (window_start + interval '1 hour' - now())))::integer);
    return;
  end if;

  current_count := current_count + 1;
  update public.otp_request_limits
  set request_count = current_count, last_requested_at = now()
  where email = normalized_email;

  return query select true, 4 - current_count, 0;
end;
$$;

revoke all on function public.claim_otp_request(text) from public;
grant execute on function public.claim_otp_request(text) to anon, authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and is_admin = true
  );
$$;

revoke all on function public.is_admin() from public;
revoke execute on function public.is_admin() from anon;
grant execute on function public.is_admin() to authenticated;

create or replace function public.set_student_academic_group(p_student_ids uuid[], p_academic_level text, p_major text)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare selected_count integer;
begin
  if not public.is_admin() then raise exception 'Administrator access required'; end if;
  if p_academic_level not in ('foundation','semester-1','semester-2','semester-3','semester-4','bachelor') then
    raise exception 'Invalid academic group';
  end if;
  if p_major not in ('CS','NW','ME','EE') then raise exception 'Invalid major'; end if;
  delete from public.academic_assignments a
  using public.profiles p
  where a.email=lower(p.email) and p.academic_level=p_academic_level and p.major=p_major
    and not (p.id=any(coalesce(p_student_ids,array[]::uuid[])));
  update public.profiles set academic_level=null, major=null, updated_at=now()
  where academic_level=p_academic_level and major=p_major and not (id=any(coalesce(p_student_ids,array[]::uuid[])));
  update public.profiles set academic_level=p_academic_level, major=p_major, updated_at=now()
  where id=any(coalesce(p_student_ids,array[]::uuid[]));
  insert into public.academic_assignments(email,academic_level,major,created_by)
  select lower(email),p_academic_level,p_major,(select auth.uid())
  from public.profiles where id=any(coalesce(p_student_ids,array[]::uuid[]))
  on conflict (email) do update set academic_level=excluded.academic_level,major=excluded.major,updated_at=now();
  select count(*) into selected_count from public.profiles where academic_level=p_academic_level and major=p_major;
  return selected_count;
end;
$$;
revoke all on function public.set_student_academic_group(uuid[],text,text) from public, anon;
grant execute on function public.set_student_academic_group(uuid[],text,text) to authenticated;
drop function if exists public.set_student_academic_level(uuid[],text);

create or replace function public.bulk_assign_academic_groups(p_entries jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare item jsonb; normalized_email text; selected_level text; selected_major text; saved_count integer:=0; registered_count integer:=0; affected integer;
begin
  if not public.is_admin() then raise exception 'Administrator access required'; end if;
  if jsonb_typeof(p_entries)<>'array' then raise exception 'Email assignments must be an array'; end if;
  for item in select value from jsonb_array_elements(p_entries) loop
    normalized_email:=lower(trim(item->>'email')); selected_level:=trim(item->>'academic_level'); selected_major:=upper(trim(item->>'major'));
    if normalized_email !~ '^[^@\s]+@(st\.auston\.edu\.mm|auston\.edu\.mm)$' then raise exception 'Invalid official Auston email: %',normalized_email; end if;
    if selected_level not in ('foundation','semester-1','semester-2','semester-3','semester-4','bachelor') then raise exception 'Invalid academic group for %',normalized_email; end if;
    if selected_major not in ('CS','NW','ME','EE') then raise exception 'Invalid major for %',normalized_email; end if;
    insert into public.academic_assignments(email,academic_level,major,created_by) values(normalized_email,selected_level,selected_major,(select auth.uid()))
    on conflict (email) do update set academic_level=excluded.academic_level,major=excluded.major,updated_at=now();
    saved_count:=saved_count+1;
    update public.profiles set academic_level=selected_level,major=selected_major,updated_at=now()
    where lower(email)=normalized_email and (academic_level is distinct from selected_level or major is distinct from selected_major);
    get diagnostics affected=row_count; registered_count:=registered_count+affected;
  end loop;
  return jsonb_build_object('saved',saved_count,'registered',registered_count);
end;
$$;
revoke all on function public.bulk_assign_academic_groups(jsonb) from public, anon;
grant execute on function public.bulk_assign_academic_groups(jsonb) to authenticated;
drop function if exists public.bulk_assign_academic_levels(jsonb);

create or replace function public.remove_academic_assignments(p_emails text[])
returns integer language plpgsql security definer set search_path = '' as $$
declare normalized_emails text[]; removed_count integer;
begin
  if not public.is_admin() then raise exception 'Administrator access required'; end if;
  select coalesce(array_agg(lower(trim(value))),array[]::text[]) into normalized_emails
  from unnest(coalesce(p_emails,array[]::text[])) as value;
  update public.profiles set academic_level=null,major=null,updated_at=now() where lower(email)=any(normalized_emails);
  delete from public.academic_assignments where email=any(normalized_emails);
  get diagnostics removed_count=row_count; return removed_count;
end;
$$;
revoke all on function public.remove_academic_assignments(text[]) from public;
grant execute on function public.remove_academic_assignments(text[]) to authenticated;

create or replace function public.promote_academic_group(
  p_from_level text,
  p_from_major text,
  p_to_level text,
  p_to_major text
)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare saved_count integer:=0; added_count integer:=0; registered_count integer:=0;
begin
  if not public.is_admin() then raise exception 'Administrator access required'; end if;
  if p_from_level not in ('foundation','semester-1','semester-2','semester-3','semester-4','bachelor')
    or p_to_level not in ('foundation','semester-1','semester-2','semester-3','semester-4','bachelor') then
    raise exception 'Invalid academic level';
  end if;
  if p_from_major not in ('CS','NW','ME','EE') or p_to_major not in ('CS','NW','ME','EE') then
    raise exception 'Invalid major';
  end if;
  if p_from_level=p_to_level and p_from_major=p_to_major then raise exception 'Choose a different destination group'; end if;

  update public.academic_assignments
  set academic_level=p_to_level,major=p_to_major,updated_at=now()
  where academic_level=p_from_level and major=p_from_major;
  get diagnostics saved_count=row_count;

  insert into public.academic_assignments(email,academic_level,major,created_by)
  select lower(p.email),p_to_level,p_to_major,(select auth.uid())
  from public.profiles p
  where p.academic_level=p_from_level and p.major=p_from_major
    and not exists (select 1 from public.academic_assignments a where a.email=lower(p.email));
  get diagnostics added_count=row_count;

  update public.profiles
  set academic_level=p_to_level,major=p_to_major,updated_at=now()
  where academic_level=p_from_level and major=p_from_major;
  get diagnostics registered_count=row_count;

  return jsonb_build_object('saved',saved_count+added_count,'registered',registered_count);
end;
$$;
revoke all on function public.promote_academic_group(text,text,text,text) from public, anon;
grant execute on function public.promote_academic_group(text,text,text,text) to authenticated;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  sid text := upper(trim(new.raw_user_meta_data ->> 'student_id'));
  student_name text := trim(new.raw_user_meta_data ->> 'full_name');
  assigned_level text;
  assigned_major text;
begin
  if new.email !~* '^[^@\s]+@(st\.auston\.edu\.mm|auston\.edu\.mm)$' then
    raise exception 'Only Auston email addresses are allowed';
  end if;
  if sid !~ '^AU[0-9]{7}$' then
    raise exception 'Student ID must match AU followed by seven digits';
  end if;
  if char_length(student_name) < 2 then
    raise exception 'Full name is required';
  end if;
  select academic_level,major into assigned_level,assigned_major from public.academic_assignments where email=lower(new.email);
  insert into public.profiles(id,email,student_id,full_name,is_admin,academic_level,major)
  values(new.id,lower(new.email),sid,student_name,lower(new.email) ~ '^[^@]+@auston\.edu\.mm$',assigned_level,assigned_major);
  return new;
end;
$$;
revoke execute on function public.handle_new_user() from public, anon, authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.academic_assignments enable row level security;
alter table public.timetable enable row level security;
alter table public.content_items enable row level security;
alter table public.otp_request_limits enable row level security;

drop policy if exists "Students read own profile" on public.profiles;
create policy "Students read own profile" on public.profiles for select to authenticated using ((select auth.uid()) = id or (select public.is_admin()));
drop policy if exists "Students update own profile" on public.profiles;
create policy "Students update own profile" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
drop policy if exists "Admins read academic assignments" on public.academic_assignments;
create policy "Admins read academic assignments" on public.academic_assignments for select to authenticated using ((select public.is_admin()));
revoke update on table public.profiles from authenticated;
grant update (full_name, program, avatar_url, updated_at) on table public.profiles to authenticated;
drop policy if exists "Students read published timetable" on public.timetable;
create policy "Students read published timetable" on public.timetable for select to authenticated using (
  ((select public.is_admin()) and source = 'official')
  or (published and target_user_id = (select auth.uid()))
  or (published and target_user_id is null and cohort = 'all' and target_major is null)
  or (published and target_user_id is null
      and cohort in ('all',coalesce((select academic_level from public.profiles where id = (select auth.uid())), 'none'))
      and target_major = (select major from public.profiles where id = (select auth.uid())))
  or (source = 'personal' and created_by = (select auth.uid()))
);
drop policy if exists "Students create personal timetable" on public.timetable;
create policy "Students create personal timetable" on public.timetable for insert to authenticated with check (
  (select public.is_admin())
  or (source = 'personal' and created_by = (select auth.uid()) and target_user_id = (select auth.uid()))
);
drop policy if exists "Students update personal timetable" on public.timetable;
create policy "Students update personal timetable" on public.timetable for update to authenticated using (
  (select public.is_admin()) or (source = 'personal' and created_by = (select auth.uid()))
) with check (
  (select public.is_admin()) or (source = 'personal' and created_by = (select auth.uid()) and target_user_id = (select auth.uid()))
);
drop policy if exists "Students delete personal timetable" on public.timetable;
create policy "Students delete personal timetable" on public.timetable for delete to authenticated using (
  (select public.is_admin()) or (source = 'personal' and created_by = (select auth.uid()))
);
drop policy if exists "Students read published content" on public.content_items;
create policy "Students read published content" on public.content_items for select to authenticated using (
  (select public.is_admin()) or (published and (target_user_id is null or target_user_id = (select auth.uid())))
);
drop policy if exists "Admins create content" on public.content_items;
create policy "Admins create content" on public.content_items for insert to authenticated with check ((select public.is_admin()));
drop policy if exists "Admins update content" on public.content_items;
create policy "Admins update content" on public.content_items for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
drop policy if exists "Admins delete content" on public.content_items;
create policy "Admins delete content" on public.content_items for delete to authenticated using ((select public.is_admin()));

grant select on table public.profiles to authenticated;
grant select on table public.academic_assignments to authenticated;
grant select, insert, update, delete on table public.timetable to authenticated;
grant select, insert, update, delete on table public.content_items to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create index if not exists profiles_academic_group_idx on public.profiles(academic_level,major);
create index if not exists academic_assignments_group_idx on public.academic_assignments(academic_level,major);
create index if not exists timetable_academic_group_idx on public.timetable(cohort,target_major)
where published and target_user_id is null;

update public.timetable set target_major='CS'
where source='official' and published and target_user_id is null
  and cohort='semester-2' and target_major is null;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('avatars','avatars',true,1800000,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=true,file_size_limit=1800000,allowed_mime_types=array['image/jpeg','image/png','image/webp'];

drop policy if exists "Avatar public read" on storage.objects;
create policy "Avatar public read" on storage.objects for select using (bucket_id='avatars');
drop policy if exists "Students upload own avatar" on storage.objects;
create policy "Students upload own avatar" on storage.objects for insert to authenticated with check (bucket_id='avatars' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists "Students update own avatar" on storage.objects;
create policy "Students update own avatar" on storage.objects for update to authenticated using (bucket_id='avatars' and owner_id=(select auth.uid()::text)) with check (bucket_id='avatars' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists "Students delete own avatar" on storage.objects;
create policy "Students delete own avatar" on storage.objects for delete to authenticated using (bucket_id='avatars' and owner_id=(select auth.uid()::text));

do $$ begin
  alter publication supabase_realtime add table public.timetable;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.content_items;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.profiles;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.academic_assignments;
exception when duplicate_object then null; end $$;

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions(user_id);
alter table public.push_subscriptions enable row level security;

drop policy if exists "push subscriptions select own" on public.push_subscriptions;
create policy "push subscriptions select own" on public.push_subscriptions
  for select using (auth.uid() = user_id);
drop policy if exists "push subscriptions insert own" on public.push_subscriptions;
create policy "push subscriptions insert own" on public.push_subscriptions
  for insert with check (auth.uid() = user_id);
drop policy if exists "push subscriptions update own" on public.push_subscriptions;
create policy "push subscriptions update own" on public.push_subscriptions
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "push subscriptions delete own" on public.push_subscriptions;
create policy "push subscriptions delete own" on public.push_subscriptions
  for delete using (auth.uid() = user_id);

-- Server-only VAPID key storage for the send-push edge function. RLS is
-- enabled with no policies, so only the service role can read this table;
-- the actual key values are inserted out-of-band, never committed here.
create table if not exists public.push_vapid_keys (
  id boolean primary key default true check (id),
  public_key text not null,
  private_key text not null,
  subject text not null default 'mailto:support@auston.edu.mm',
  updated_at timestamptz not null default now()
);
alter table public.push_vapid_keys enable row level security;

grant select, insert, update, delete on table public.push_subscriptions to authenticated;

commit;
