create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions(user_id);
alter table public.push_subscriptions enable row level security;

drop policy if exists "push subscriptions select own" on public.push_subscriptions;
create policy "push subscriptions select own" on public.push_subscriptions
  for select using (auth.uid() = user_id);
drop policy if exists "push subscriptions insert own" on public.push_subscriptions;
create policy "push subscriptions insert own" on public.push_subscriptions
  for insert with check (auth.uid() = user_id);
drop policy if exists "push subscriptions update own" on public.push_subscriptions;
create policy "push subscriptions update own" on public.push_subscriptions
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "push subscriptions delete own" on public.push_subscriptions;
create policy "push subscriptions delete own" on public.push_subscriptions
  for delete using (auth.uid() = user_id);

-- Server-only VAPID key storage for the send-push edge function. RLS is
-- enabled with no policies, so only the service role can read this table;
-- the actual key values are inserted out-of-band, never committed here.
create table if not exists public.push_vapid_keys (
  id boolean primary key default true check (id),
  public_key text not null,
  private_key text not null,
  subject text not null default 'mailto:support@auston.edu.mm',
  updated_at timestamptz not null default now()
);
alter table public.push_vapid_keys enable row level security;

grant select, insert, update, delete on table public.push_subscriptions to authenticated;
grant usage, select on all sequences in schema public to authenticated;
